Upload question and cron-job validation
Assisted-Math-Learning/aml-jobs-service pull request #1
Opened 2024-09-05 13:12 UTC by Novfal-202

1.question upload Api completed.
2.get uploaded question Api completed.
3.upload status Api completed.
4.get and uploaded template completed.
4. Cron job for validating the question  structure and format of the CSV file .

2024-09-11 13:10 UTC, Hari-1027 commented on src/app.ts
> +      .then(() => logger.info('Database connection successful'))
please remove this

2024-09-11 13:11 UTC, Hari-1027 commented on src/config/config.ts
> +    port: Number(get(envVars, 'AML_SERVICE_DB_PORT')),
add alternative port

2024-09-11 13:14 UTC, Hari-1027 commented on src/app.ts
> +      .catch((err: any) => logger.error('Error in database connection', { message: err.message }));
please compare the main repo and correct all common comments.

2024-09-11 13:15 UTC, Hari-1027 commented on src/controllers/BulkUpload/questionStatusJob.ts
> +const checkStatus = new CronJob('0 9,21 * * *', async () => {
this is configurable. the cron timer should not be inside the controller

2024-09-12 04:49 UTC, Novfal-202 commented on src/app.ts
> +      .then(() => logger.info('Database connection successful'))
updated

2024-09-12 04:49 UTC, Novfal-202 commented on src/app.ts
> +      logger.info(`Listening on port.`);
updated

2024-09-12 05:01 UTC, Novfal-202 commented on src/config/config.ts
> +    port: Number(get(envVars, 'AML_SERVICE_DB_PORT')),
updated

2024-09-12 08:51 UTC, Novfal-202 commented on src/app.ts
> +      .catch((err: any) => logger.error('Error in database connection', { message: err.message }));
changes completed

2024-09-12 08:51 UTC, Novfal-202 commented on src/controllers/BulkUpload/questionStatusJob.ts
> +const checkStatus = new CronJob('0 9,21 * * *', async () => {
updated

2024-09-12 08:51 UTC, Novfal-202 commented on src/controllers/BulkUpload/questionStatusJob.ts
> +        case 'fib.zip':
updated

2024-09-16 07:39 UTC, HarishGangula requested changes

2024-09-16 07:39 UTC, HarishGangula commented on .env.example
> +BUCKET_NAME=aml-dev-otsv83nane
Replace with dummy data

2024-09-16 07:39 UTC, HarishGangula commented on Dockerfile
> +RUN apk add --no-cache postgresql-client
Removed it

2024-09-16 07:39 UTC, HarishGangula commented on package.json
> +  "license": "ISC",
MIT

2024-09-16 07:39 UTC, HarishGangula commented on src/controllers/BulkUpload/questionStatusJob.ts
> +      const { getProcess } = processInfo;
1. Get the Zip file if not throw error
2. validate zip file contents if not throw error
3. validate the content in each file if not throw error
4. process the request 
5. insert to staging table
6. process each entity(question, question set, content) if not throw error
7. update the process status - successful

2024-09-17 10:46 UTC, Novfal-202 commented on src/controllers/BulkUpload/questionStatusJob.ts
> +      const { getProcess } = processInfo;
Upto second point in these PR .next point are merge once the initial PR merged.

2024-09-17 10:47 UTC, Novfal-202 commented on package.json
> +  "license": "ISC",
updated.

2024-09-17 10:47 UTC, Novfal-202 commented on Dockerfile
> +RUN apk add --no-cache postgresql-client
updated

2024-09-17 10:47 UTC, Novfal-202 commented on .env.example
> +BUCKET_NAME=aml-dev-otsv83nane
updated.

2024-09-17 10:47 UTC, Novfal-202 commented on .env.example
> +AML_SERVICE_DB_NAME=bulk_upload_service
updated.

2024-09-17 10:47 UTC, Novfal-202 commented on .env.example
> +AML_SERVICE_APPLICATION_ENV = "development"
updated.

2024-09-20 09:17 UTC, Novfal-202 commented on .env.example
> +AML_SERVICE_APPLICATION_ENV = "development"
removed

2024-09-20 09:17 UTC, Novfal-202 commented on .env.example
> +AML_SERVICE_DB_NAME=bulk_upload_service
updated.

2024-09-20 09:18 UTC, Novfal-202 commented on .env.example
> +BUCKET_NAME=aml-dev-otsv83nane
bucket name updated as dummy Bucket

2024-09-20 09:20 UTC, Novfal-202 commented
As per mentioned changes and modification completed.

2024-09-24 07:26 UTC, HarishGangula commented
{
error:  bulkUploadError
data: null
}


{
error:  null
data: {
isValid: true
}
}

{
error:  null
data: {
zipContents: []
}
}

2024-09-26 04:53 UTC, Novfal-202 commented
@HarishGangula PR updated with latest changes .

2024-09-26 11:52 UTC, HarishGangula approved these changes

2024-09-26 11:53 UTC, HarishGangula commented
Merging with implementation, Need to test with Actual data

2024-09-26 11:53 UTC, merged