Mcq image field updated
Assisted-Math-Learning/aml-jobs-service pull request #6
Opened 2024-10-14 08:40 UTC by Novfal-202

Missed functionality for adding mcq image in cloud and storing reference in respective field.

2024-10-14 09:03 UTC, Novfal-202 commented
@HarishGangula could you review these PR .

2024-10-15 05:46 UTC, HarishGangula requested changes

2024-10-15 05:46 UTC, HarishGangula commented on src/controllers/question.ts
> +            obj?.question_type === 'Mcq' ? [mcq_option_1, mcq_option_2, mcq_option_3, mcq_option_4, mcq_option_5, mcq_option_6].filter((option) => option !== null && option.trim() !== '') : undefined
convert to lowercase and compare

2024-10-15 05:46 UTC, HarishGangula commented on src/controllers/question.ts
> +      if (question_type === 'Mcq' && mcq_question_image) {
convert to lowercase and compare

2024-10-15 05:49 UTC, Novfal-202 commented on src/controllers/question.ts
> +      if (question_type === 'Mcq' && mcq_question_image) {
Currently, for both question type and L1 skill, the first letter is capitalised, followed by lowercase letters. This approach has also been discussed with the content team.

2024-10-15 05:49 UTC, Novfal-202 commented on src/controllers/question.ts
> +            obj?.question_type === 'Mcq' ? [mcq_option_1, mcq_option_2, mcq_option_3, mcq_option_4, mcq_option_5, mcq_option_6].filter((option) => option !== null && option.trim() !== '') : undefined
Currently, for both question type and L1 skill, the first letter is capitalized, followed by lowercase letters. This approach has also been discussed with the content team.

2024-10-15 06:54 UTC, HarishGangula requested changes

2024-10-15 06:54 UTC, HarishGangula commented on src/controllers/question.ts
> +            obj?.question_type.toLowerCase() === 'mcq'
add optional chaining for toLowerCase method also

2024-10-15 06:54 UTC, HarishGangula commented on src/controllers/question.ts
> +      if (question_type.toLowerCase() === 'mcq' && mcq_question_image) {
add optional chaining for toLowerCase method also

2024-10-15 07:06 UTC, Novfal-202 commented on src/controllers/question.ts
> +            obj?.question_type.toLowerCase() === 'mcq'
updated.

2024-10-15 07:06 UTC, Novfal-202 commented on src/controllers/question.ts
> +      if (question_type.toLowerCase() === 'mcq' && mcq_question_image) {
updated

2024-10-15 07:15 UTC, HarishGangula approved these changes

2024-10-15 07:15 UTC, merged